export enum Actions {
  START_FETCHING = 'START_FETCHING',
  ERROR_FETCHING = 'ERROR_FETCHING',
  FINISH_FETCHING = 'FINISH_FETCHING',
  INIT_REQUEST_SUCCESS = 'INIT_REQUEST_SUCCESS',
  CREATE_ACCOUNT_REQUEST_SUCCESS = 'CREATE_ACCOUNT_REQUEST_SUCCESS',
  EDIT_ACCOUNT_REQUEST_SUCCESS = 'EDIT_ACCOUNT_REQUEST_SUCCESS',
  DELETE_ACCOUNT_REQUEST_SUCCESS = 'DELETE_ACCOUNT_REQUEST_SUCCESS',
  UPDATE_ENABLED_ACCOUNTS_REQUEST_SUCCESS = 'UPDATE_ENABLED_ACCOUNTS_REQUEST_SUCCESS',
  ADD_PAGE_ALERT = 'ADD_PAGE_ALERT_REQUEST',
  REMOVE_PAGE_ALERT = 'REMOVE_PAGE_ALERT_REQUEST'
}
